### PR TITLE
accept only supported image formats

### PR DESCRIPTION
**Pull request by stelin41**
Some image formats are not supported, this prevents the user from trying to upload them.

### CODE REVIEW

**Comment by Birddude1230** [comment]
this seems like a worthwhile idea if you can extract the supported filetypes from the man of gabbo

**Comment by gabboman** [comment]
Seems like a great idea

**Comment by Birddude1230** [comment]
you will contribute whether you want to or not

**Comment by stelin41** [comment]
lol this was my first pull request, so I wasn't sure if I was doing it right

**Pull request merged**
